dist: trusty
sudo: required

language: python
python:
  - "2.7"
  - "3.4"

os:
  - linux

branches:
  only:
    - master
    - /^\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  - NAME=greeter_plugin BAZEL=0.9.0 TF=NIGHTLY
  - NAME=greeter_tensorboard BAZEL=0.9.0 TF=NIGHTLY

cache:
  directories:
    - $HOME/.bazel-output-base

before_install:
  - |
    set -e
    BAZEL_URL="https://github.com/bazelbuild/bazel/releases/download/${BAZEL}/bazel-${BAZEL}-installer-linux-x86_64.sh"
    wget -t 3 -O install.sh "${BAZEL_URL}"
    chmod +x install.sh
    ./install.sh --user
    rm -f install.sh

  - |
    case "${TF}" in
      RELEASE)
        pip install tensorflow
        ;;
      NIGHTLY)
        pip install -I tf-nightly
        ;;
      *)
        pip install tensorflow=="${TF}"
        ;;
    esac

  - pip install pylint
  - pip install futures==3.1.1
  - pip install grpcio==1.4.0

script:
  - |
    bazel \
      --output_base="${HOME}/.bazel-output-base" \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      build \
      "//${NAME}/..." \
      --worker_verbose \
      --verbose_failures \
      --spawn_strategy=sandboxed \
      --genrule_strategy=sandboxed \
      --local_resources=400,2,1.0 \
      --worker_max_instances=2 \
      --strategy=Javac=worker \
      --strategy=Closure=worker

  # TODO(@jart): Uncomment when tests are added.
  # - |
  #   bazel \
  #     --output_base="${HOME}/.bazel-output-base" \
  #     --batch \
  #     --host_jvm_args=-Xmx500m \
  #     --host_jvm_args=-Xms500m \
  #     test \
  #     "//${NAME}/..." \
  #     --verbose_failures \
  #     --test_output=errors \
  #     --spawn_strategy=sandboxed \
  #     --local_resources=400,2,1.0

  - |
    # DIR=$(pwd)
    # cd bazel-genfiles
    # find "${NAME}" -name \*.py -exec cp {} "${DIR}"/{} \;
    # cd "${DIR}"
    pylint "${NAME}"

before_cache:
  - |
    find "${HOME}/.bazel-output-base" \
      -name \*.runfiles -print0 \
      -or -name \*.tar.gz -print0 \
      -or -name \*-execroot.json -print0 \
      -or -name \*-tsc.json -print0 \
      -or -name \*-params.pbtxt -print0 \
      -or -name \*-args.txt -print0 \
      -or -name \*.runfiles_manifest -print0 \
      -or -name \*.server_params.pbtxt -print0 \
      | xargs -0 rm -rf

notifications:
  email: false
