name: tensorboard27
channels:
- defaults
dependencies:
- certifi=2016.2.28=py27_0
- openssl=1.0.2l=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=36.4.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - backports.weakref==1.0.post1
  - chardet==3.0.4
  - cycler==0.10.0
  - cython==0.26.1
  - decorator==4.1.2
  - enum34==1.1.6
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - futures==3.1.1
  - grpc==0.3.post19
  - grpcio==1.6.0
  - h5py==2.7.1
  - idna==2.6
  - leveldb==0.194
  - matplotlib==2.0.2
  - mock==2.0.0
  - msgpack-python==0.4.8
  - networkx==1.11
  - nose==1.3.7
  - numpy==1.13.1
  - olefile==0.44
  - pandas==0.20.3
  - pbr==3.1.1
  - pillow==4.2.1
  - protobuf==3.4.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - python-gflags==3.1.1
  - pytz==2017.2
  - pywavelets==0.5.2
  - pyyaml==3.12
  - requests==2.18.4
  - scikit-image==0.13.0
  - scipy==0.19.1
  - six==1.10.0
  - subprocess32==3.2.7
  - tf-nightly
  - urllib3==1.22

